### PR TITLE
[Breaking] Remove the statsd metrics, dependency no more available 

### PR DESCRIPTION
**Pull request by sbrunner**
To be continued:
- https://mvnrepository.com/artifact/com.readytalk/metrics3-statsd/4.2.0
- https://github.com/mapfish/mapfish-print/pull/379
- https://github.com/prometheus/jmx_exporter/blob/master/README.md
- https://medium.com/logistimo-engineering-blog/tomcat-jvm-metrics-monitoring-using-prometheus-in-kubernetes-c313075af727
- https://mvnrepository.com/artifact/io.prometheus.jmx/jmx_prometheus_javaagent

### CODE REVIEW

**Review by pmauduit — CHANGES_REQUESTED** [review]
Why not removing the StatsDReporterInit class totally ? The class looks pretty useless to me after your PR

**Comment by sbrunner** [comment]
Good catch @pmauduit thanks, fixed :-)

**Comment by sbrunner** [comment]
@pmauduit fixed

**Comment by pmauduit** [comment]
Looks almost good to me, but the class is still referenced here and you should end up with a ClassNotFoundException / NoClassDefFoundError if you don't remove the following line:
https://github.com/mapfish/mapfish-print/blob/befa4bbf53e646d457fa85b127cf598baa5fc8d2/core/src/main/resources/mapfish-spring-application-context.xml#L69

**Comment by sbrunner** [comment]
@pmauduit this is already removed, you point an old commit...

**Comment by sbrunner** [comment]
@pmauduit up...

**Comment by sbrunner** [comment]
@pmauduit up...

**Review by pmauduit — APPROVED** [review]
LGTM

**Pull request merged**
