### PR TITLE
Improve documentation

### LINKED ISSUE #209: Documentation is built from the wrong version?
http://mapfish.github.io/mapfish-print-doc/#/downloads is built against version 3.2-SNAPSHOT which never got pushed to sonatype (or has been deleted) this means the links are broken as there is a 3.1-SNAPSHOT directory and a 3.3-SNAPSHOT but no 3.2-SNAPSHOT.  See https://oss.sonatype.org/content/repositories/snapshots/org/mapfish/print/print-servlet/

### LINKED ISSUE #328: Parameters are written in an human readable way
Parameters in the documentation are written in an human readable way which is wrong if you want to use it in the config.yaml.

See http://mapfish.github.io/mapfish-print-doc/#/processors#!createDataSource
```
Input Mapper

The input mapper.
```

`Input Mapper` should be `inputMapper`

### LINKED ISSUE #353: Documentation for styles is broken
See http://mapfish.github.io/mapfish-print-doc/#/styles

### PR DESCRIPTION
**Pull request by tsauerwein**
This PR is a major rework of the documentation.

mfp-docs-1
mfp-docs-2
mfp-docs-3

Closes #353 
Closes #328 
Closes #209

### CODE REVIEW

**Comment by sbrunner** [comment]
Difficult to review...
The that's look relay good :-)
just a small comment then for me you can merge.

**Comment by tsauerwein** [comment]
Thanks!

**Comment by tsauerwein** [comment]
I updated the online version: http://mapfish.github.io/mapfish-print-doc/

**Comment by sbrunner** [comment]
Thanks @tsauerwein :-)

**Pull request merged**
