### PR TITLE
Render labels that are partially outside the viewport

### PR DESCRIPTION
**Pull request by tsauerwein**
When rendering labels, where the geometry is inside the viewport bbox but a part of the label would be outside, the label is not rendered by default with GeoTools.

Setting the option [partials](http://docs.geotools.org/latest/javadocs/org/geotools/styling/TextSymbolizer.html#DEFAULT_PARTIALS) to `true` also includes these labels.

The issue was originally reported on the mailing-list: https://groups.google.com/forum/#!topic/mapfish-print-users/oRg73GxVwAg

Requires an update of GeoTools, see https://github.com/mapfish/mapfish-print/pull/424

### CODE REVIEW

**Comment by sbrunner** [comment]
648dd87975279f7d4554a5179ee46a1710f40552 looks relay good :-)

**Comment by tsauerwein** [comment]
Ok for merging this one?

**Comment by sbrunner** [comment]
Shouldn't be false by default?

**Comment by tsauerwein** [comment]
> Shouldn't be false by default?

If `partials` is set to `false`, labels are not visible if parts of the labels are outside the viewport. In my opinion the default should be that labels are always visible (`partials: true`).

**Comment by sbrunner** [comment]
Personally I don't agree, And usually we don't do that, for example when we get a map with map-server, a feature that's not in the extent isn't visible at all.
And we have an option to force that the visible labels that will not be cuted...
For me that have more sense...

**Comment by tsauerwein** [comment]
> ... a feature that's not in the extent isn't visible at all.

This is all about features that are in the extent. You have a point that is in the extent that you want to print. But when a part of the label for this point would be outside the extent, the label would not be rendered.

**Comment by sbrunner** [comment]
Sorry for misunderstood, looks good, merge :-)

**Comment by tsauerwein** [comment]
Thanks for the review!

**Pull request merged**
