### PR TITLE
Log errors if request fails in http cache

### PR DESCRIPTION
**Pull request by tsauerwein**
Closes https://github.com/mapfish/mapfish-print/issues/491

### CODE REVIEW

**Comment by tsauerwein** [comment]
Responses for requests with a status code other than 200 are also cached. The users of the cache (e.g. layers) can decide what they do in such a case. But that is not the point of this PR.

**Comment by sbrunner** [comment]
> But that is not the point of this PR.

Not directly but it's good to understand the context :-)

> The users of the cache (e.g. layers) can decide what they do in such a case.

I try to find some more informations here: http://mapfish.github.io/mapfish-print-doc/layers.html without any success... How is it working?

**Comment by tsauerwein** [comment]
> > The users of the cache (e.g. layers) can decide what they do in such a case.
> 
> I try to find some more informations here: http://mapfish.github.io/mapfish-print-doc/layers.html without any success... How is it working?

By "users of the cache" I mean the layer classes which get the request responses from the cache and decide for example if a pink image is rendered or the print fails. Users of MFP can configure this behavior with `failOnError`, see http://mapfish.github.io/mapfish-print-doc/layers.html

**Comment by tsauerwein** [comment]
Merging because no functional change, this PR is only adding logging statements.
@sbrunner, if you want to change the behavior of the error handling, I'd propose to do this in a new PR.

**Pull request merged**
