### PR TITLE
Fix some security issues

### PR DESCRIPTION
**Pull request by sbrunner**
Fix: GSGMF-1331

### CODE REVIEW

**Comment by gurshafriri** [comment]
👋 @sbrunner, can you elaborate a bit more about the issues at hand? 
Im from [Snyk](snyk.io) and if these are indeed vulnerabilities we would like to add it to our database with full context.

**Comment by sbrunner** [comment]
@gurshafriri 
I just change the title, for me, its potential security vulnerabilities detected by CodeQL I provide the links in the commits, all fixed issues:
- https://github.com/mapfish/mapfish-print/security/code-scanning/3?query=ref%3Arefs%2Fheads%2Fmaster
- https://github.com/mapfish/mapfish-print/security/code-scanning/5?query=ref%3Arefs%2Fheads%2Fmaster
- https://github.com/mapfish/mapfish-print/security/code-scanning/6?query=ref%3Arefs%2Fheads%2Fmaster
- https://github.com/mapfish/mapfish-print/security/code-scanning/7?query=ref%3Arefs%2Fheads%2Fmaster

**Comment by sbrunner** [comment]
I also publish my 2 first GitHub Security Advisories.

**Comment by gurshafriri** [comment]
@sbrunner thanks - but the links are broken for us. 
Do you have the GitHub Security Advisory ID's?

**Comment by sbrunner** [comment]
Like this?
* https://github.com/mapfish/mapfish-print/security/advisories/GHSA-w534-q4xf-h5v2
* https://github.com/mapfish/mapfish-print/security/advisories/GHSA-vjv6-gq77-3mjw

**Pull request merged**
