### PR TITLE
adding legacy xyz layer + conversion from old api

### PR DESCRIPTION
**Pull request by didier-coignet-dict**
for backward compatibility it would be nice to add legacy xyz layer

### CODE REVIEW

**Comment by jesseeichar** [comment]
Looks great.

**Comment by tsauerwein** [comment]
One question: How is this XYZ layer different to the OSM layer? Couldn't you create a OSM layer from a XYZ layer definition (in the `OldAPILayerConverter`)?

**Comment by jesseeichar** [comment]
They are quite similar, but if I remember right there are some assumptions for the layers that are not the same.  I could be that we could make the API for OSM more rich to support XYZ but it might complicate OSM and having it separate might actually make the system simpler for the user (and maybe developers).

Do you want me to wait to merge this?

**Comment by tsauerwein** [comment]
As far as I can see the only difference is the parameter `customParams` (https://github.com/didier-coignet-dict/mapfish-print/blob/da3c52c45ee30bf232f7505b82d98a2500441ea7/core/src/main/java/org/mapfish/print/map/tiled/xyz/XyzLayerParam.java#L105). The rest seems to be a 1:1 copy of the OSM layer.

If it's really just this one parameter, I wouldn't mind adding it to the OSM layer. Especially to avoid all the duplicated code.

**Comment by jesseeichar** [comment]
If that is the only difference then I agree, we shouldn't have this plugin.

**Comment by didier-coignet-dict** [comment]
Yes that's true the only difference is the addition of customParams. 
The code has been duplicated because they are separated layers in v2 (tiles resolution might be slightly different in V2 between xyz and osm) and this plugin comes from an override in our own application to be able to use mapbox.
Feel free to reject this pull request if needed .

**Comment by tsauerwein** [comment]
No, it would be good to have this compatibility with the old XYZ layers. I am just trying to understand, why a separate layer type would be needed in MFP 3.

> (tiles resolution might be slightly different in V2 between xyz and osm)

But the resolutions that you are using for the layer XYZ are the same as for layer OSM, right?

I would propose to add the parameter `customParams` to the OSM layer type and make the `OldAPILayerConverter` create a OSM layer when trying to convert an old XYZ layer. What do you think? Would this solve your problem?

**Comment by jesseeichar** [comment]
@didier-coignet-dict could you look at the osm implementation in this new version to see if it can be used for you if customParams is added to it?

**Comment by didier-coignet-dict** [comment]
Yes it would be perfect.
The new implementation of osm layer merges the implementations of xyz and osm in the old implementation.
Adding customParams is necessary for acces tokens.

**Comment by jesseeichar** [comment]
Can you make a PR of OSM updated with customParams?

**Comment by didier-coignet-dict** [comment]
Yes

**Comment by jesseeichar** [comment]
Cool.  I will close this PR and wait for the next one.

**Pull request closed without merging**
