### PR TITLE
Scale, geodetic

### PR DESCRIPTION
**Pull request by sbrunner**
* Partially revert #212 
* Add Geodetic scale methods in MapContext
* Calculate Scalebar on MapContext see #264 issue
* Be able to snap on Geodetic scales

### CODE REVIEW

**Comment by sbrunner** [comment]
Ready for a review !

**Comment by tsauerwein** [comment]
Looks good to me! I hope this fixes our problems with the scale.

**Comment by sbrunner** [comment]
Thanks @tsauerwein :-)

**Comment by didier-coignet-dict** [comment]
Thanks it works.
if anybody needs to use a geodetic projection with scalebar and displayed scale as : 

You need to add values in all three configuration files. 

#### In  config.yaml
to have Geodetic Zoom level snapping you need :

 * useNearestScale: true
 * zoomSnapGeodetic: true

#### In  requestData.json
To generate the scalebar with geodetic calculations :

 * $.scalebar.geodetic: true

#### In  report.jrxml
to display the scale as text like '1:1000' use :

    <![CDATA[String.format("1:%.0f", $P{mapContext}.getGeodeticScale().getDenominator())]]>
    or 
    <![CDATA[String.format("1:%.0f", $P{mapContext}.getRoundedScale(true))]]>
instead of   

    <![CDATA[String.format("1:%.0f", $P{mapContext}.getScale().getDenominator())]]>
    or 
    <![CDATA[String.format("1:%.0f", $P{mapContext}.getRoundedScale())]]>


An example can be found here https://gist.github.com/didier-coignet-dict/c1ba91cd69c9df9d0c20/raw/5f25217c8acb160c169732a2a284a4299ace6bb9/scalebarGeodetic.zip

**Comment by sbrunner** [comment]
Thanks @didier-coignet-dict for the short complementary :-)

**Comment by elemoine** [comment]
Thanks @didier-coignet-dict. This should probably be part of the MapFish Print documentation.

**Pull request merged**
