### PR TITLE
Upgrade Ubuntu to fix the build

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by bhoefling-c2c** [comment]
- You update "runs-on" for the main.yml workflow. But you keep it at "18.04" for the codeql.yaml and backport.yaml workflow. Is this intended?
- Could you please make ensure that formatting is kept intact when commiting, or if necessary separate formatting and code changes? Otherwise it makes a one-liner into a great challenge :-) Thanks [OK for this one, I found the relevant line].

**Comment by sbrunner** [comment]
I update the Ubuntu version of the main workflow because one of the deep version is no more installable on the old Ubuntu version
See also: https://github.com/mapfish/mapfish-print/runs/1867702834?check_suite_focus=true

> Could you please make ensure that formatting is kept intact when commiting, or if necessary separate formatting and code changes? Otherwise it makes a one-liner into a great challenge :-) Thanks [OK for this one, I found the relevant line].

Yes, sure :-/

**Comment by sbrunner** [comment]
And not the CodeQL because his java version didn't yet work on the new Ubuntu version...

**Comment by bhoefling-c2c** [comment]
Ah, OK then.

**Review by bhoefling-c2c — APPROVED** [review]

**Pull request merged**
