### PR TITLE
Java 8 support

### PR DESCRIPTION
**Pull request by jesseeichar**
Changes to support java 8

### CODE REVIEW

**Comment by Jenselme** [comment]
Hi,

I just tested this branch and I managed to build it with java 8. Can someone review it and merge it? I am afraid I don't know MFP enough to provide a good evaluation of the code.

**Comment by tsauerwein** [comment]
Thanks for the reminder, I will try to take a look at it this week.

**Comment by Jenselme** [comment]
Any progress?

**Comment by tsauerwein** [comment]
Sorry for the delay. I tested, but had some problems running all tests successfully on my development system. I will need some more time to investigate.

**Comment by Jenselme** [comment]
Hi,

Any progress? I would like this feature.

**Comment by tsauerwein** [comment]
Thanks a lot, Jesse! I rebased your branch and made my tests. It works great.

**Pull request merged**
