### PR TITLE
Revert "Rename useHttpForHttps to portMapping"

### PR DESCRIPTION
**Pull request by sbrunner**
This reverts commit 2076c795a6e54cbdea24cc65278e0e23d20857aa.

Bad idea useHttpForHttps don't do relay a portMapping ...

### CODE REVIEW

**Comment by tsauerwein** [comment]
Can you explain?

**Comment by sbrunner** [comment]
The useHttpForHttps do something only if the request is on the schema `https` and also change the schema to `http`...

**Comment by sbrunner** [comment]
https://github.com/sbrunner/mapfish-print/blob/revert/core/src/main/java/org/mapfish/print/processor/http/UseHttpForHttpsProcessor.java#L90
https://github.com/sbrunner/mapfish-print/blob/revert/core/src/main/java/org/mapfish/print/processor/http/UseHttpForHttpsProcessor.java#L179

**Comment by tsauerwein** [comment]
Ok, then feel free to revert.

**Comment by sbrunner** [comment]
Thanks @tsauerwein

**Pull request merged**
