### PR TITLE
How-to for tables containing HTML images

### PR DESCRIPTION
**Pull request by marionb**
- Add docu explaining how to configure tables containing HTML images

### CODE REVIEW

**Comment by tsauerwein** [comment]
Thanks, this is looking good. I only added some comments.

**Comment by marionb** [comment]
@tsauerwein about your comment concerning the configuration in the [jrxml](https://github.com/marionb/mapfish-print/commit/ecda4a159c4e32f1d0a15018089577a896967cc6#diff-5d201a1790ae1d71b4989f5cb9b1f498R95). I had a look at this in the case of BL and what happens if I removed the image element is that the whole [column was moved to the left](https://github.com/mapfish/mapfish-print/files/66410/GeoView_BL.29.pdf). If I remove the Text element I get a print error. If I have both elements I got the expected result.

**Comment by tsauerwein** [comment]
> I had a look at this in the case of BL and what happens if I removed the image element is that the whole column was moved to the left.

Did you also change the position of the text element (` x="0" y="0"`)?

**Comment by marionb** [comment]
You are right, thanks. I changed it.

**Comment by tsauerwein** [comment]
Thanks for testing! Could you please fix the two typos? After that we can merge.

**Comment by marionb** [comment]
@tsauerwein I corrected the typos. Is it possible to merge this? 
I do not have the rights to merge this.

**Comment by tsauerwein** [comment]
Thanks!

**Pull request merged**
