### PR TITLE
The ImageFormat was inconsistent

### PR DESCRIPTION
**Pull request by sbrunner**
In WMS layer it should be image/...
In WMTS REST layer it should be image/...
In WMTS KVP layer it should be png or jpeg !!

Now we are allowed to put image/... in the WMTS KVP.

fix https://github.com/camptocamp/c2cgeoportal/issues/1356

### CODE REVIEW

**Comment by tsauerwein** [comment]
For WMS and WMTS REST, can you also use "png" AND "image/png"? Or only "image/png". If we want to be consistent both should now be supported.

**Comment by sbrunner** [comment]
``png`` is not a format but an extension than you want to add inconsistency ?

**Comment by tsauerwein** [comment]
> `png` is not a format but an extension than you want to add inconsistency ?

With the change you made, it is now possible to use `image/png` and `png` as value for `imageFormat` when using WMTS KVP. My question is: Is it the same for WMS and WMTS REST?

**Comment by sbrunner** [comment]
No because the `png` value is only to don't break the issue in the released API :-(

**Comment by tsauerwein** [comment]
I understand that you want to keep backward compatibility. But your PR, which aims to make the API more consistent, introduces a new inconsistency. You can use `png` for WMTS KVP, but not for WMS and WMTS REST. How is that consistent?

If we really want to be consistent, we should support `png` and `image/png` for WMS, WMTS REST and WMTS KVP.

> png is not a format but an extension than ...

PNG is an image format which uses `png` as file extension.

**Comment by sbrunner** [comment]
Pull request updates as it should be.

**Comment by sbrunner** [comment]
> PNG is an image format which uses `png` as file extension.

Saying that PNG is an image format is a language abuse no standard use it ...

**Comment by jesseeichar** [comment]
Does this break requests from the old API?

**Comment by sbrunner** [comment]
Now yes but previously not ...

**Comment by jesseeichar** [comment]
Can you then provide an adapter in the OLD API so that old clients still work? I have several clients that use the old API and this breakage will be a real issue for those projects

**Comment by sbrunner** [comment]
OK, done :-)

**Comment by tsauerwein** [comment]
@sbrunner Can you confirm that using `image/png` and `png` as `imageFormat` is supported by WMTS Rest? Because it is for WMTS KVP and [WMS](https://github.com/mapfish/mapfish-print/blob/development/core/src/main/java/org/mapfish/print/map/image/wms/WmsLayerParam.java#L99).

**Comment by sbrunner** [comment]
I confirm that's not working because I didn’t introduce awful things !
I repeat `png` is not an image format in any OGC standard and probably all other !

**Comment by tsauerwein** [comment]
> I confirm that's not working because I didn’t introduce awful things !

Well, we are doing this "awful thing" for WMTS KVP and WMS. Your PR is about making the API more consistent for the user. I don't see how you want to explain to the user that you can use `image/png` and `png` for WMTS KVP and WMS, but only `image/png` for WMTS REST.

> I repeat png is not an image format in any OGC standard and probably all other !

The `imageFormat`parameter in MFP is not the same as the `format` parameter in the OGC specs. In MFP `imageFormat` is used for all tiled image layers (including OSM layers), see:
https://github.com/mapfish/mapfish-print/blob/b29dcc21afb709a7bcb3abc52e9c715f4c12b350/core/src/main/java/org/mapfish/print/map/tiled/AbstractTiledLayerParams.java#L43-L49

If we want to progress with this PR I would ask you to do the following things:

 * Make sure that the OSM layer and WMTS Rest support the values `image/png` and `png` as `imageFormat`.
 * [Document](https://github.com/mapfish/mapfish-print/blob/b29dcc21afb709a7bcb3abc52e9c715f4c12b350/core/src/main/java/org/mapfish/print/map/tiled/AbstractTiledLayerParams.java#L43-L49) that both ways are supported.

Thanks.

**Comment by sbrunner** [comment]
@tsauerwein  do your ***awful*** think you want => #256

**Comment by elemoine** [comment]
If I may… I personally think it's ok to be permissive and support both `image/png` and `png` for `imageFormat` in the print spec. But to me the most important thing is consistency. So either we don't support the short notation at all, or we support it for every layer type. My 2 cents.

**Pull request closed without merging**
