### PR TITLE
Use Docker container for Geoserver instead of repo

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by danduk82** [comment]
@sbrunner  mmh, does this work? I see that gradle is struggling to find geoserver dependencies in the CI

**Comment by danduk82** [comment]
moreover, do you think it can be related to: https://github.com/mapfish/mapfish-print/issues/1251

**Comment by sbrunner** [comment]
No, it doesn't work :-(, no relation with #1251

**Comment by danduk82** [comment]
@sbrunner , I just got this from @cmangeat  : https://www.osgeo.org/foundation-news/new-osgeo-repo/

**Comment by cmangeat** [comment]
seems to build better (21%...) with

cmangeat@wrk56:~/sources/mapfish-print ((tags/3.21.4) *$%)$ git diff build.gradle examples/build.gradle
diff --git a/build.gradle b/build.gradle
index 80e9e4d6..5989daab 100644
--- a/build.gradle
+++ b/build.gradle
@@ -51,6 +51,7 @@ task appRun(type: AppStartTask) {
 configure(subprojects.findAll { ['core', 'examples', 'docs'].contains(it.name) }) {
     repositories {
         mavenLocal()
+        maven { url 'https://repo.osgeo.org/repository/release' }
         maven { url "http://download.osgeo.org/webdav/geotools" }
         mavenCentral()
         maven { url "https://dl.bintray.com/readytalk/maven" }
diff --git a/examples/build.gradle b/examples/build.gradle
index d266875d..34caa5c4 100644
--- a/examples/build.gradle
+++ b/examples/build.gradle
@@ -6,7 +6,7 @@ apply plugin: 'org.gretty'
 def geoserverVersion = "2.8.2"
 repositories {
-    maven { url 'http://repo.boundlessgeo.com/main' }
+    maven { url 'https://repo.osgeo.org/repository/release' }
     maven { url 'http://maven.restlet.org' }
     jcenter()
 }

**Comment by sbrunner** [comment]
Thanks, but I prefer having a separate container instead of having everything in the same strange (for me) application.

**Pull request merged**
