### PR TITLE
Added the possibility to have reject URL matchers.

### PR DESCRIPTION
**Pull request by pvalsecc**
Now, all the matchers in \!restrictUris can have a "reject: true"
option to make them reject an URL if it matches.

### CODE REVIEW

**Comment by sbrunner** [comment]
Than this can be a good configuration for GeoMapFish ?
```yaml
- !restrictUris
  matchers:
    - !localMatch
       pathRegex : ^/<instanceid>/wsgi/mapserv_proxy.+$
    - !ipMatch
      ip : 10.0.0.0
      mask : 255.0.0.0
      reject: true
    - !ipMatch
      ip : 172.16.0.0
      mask : 255.240.0.0
      reject: true
    - !ipMatch
      ip : 192.168.0.0
      mask : 255.255.0.0
      reject: true
    - !acceptAll
```

**Comment by pvalsecc** [comment]
LGTM

We just have to be careful if we have a mapserver on another Amazon
instance. Amazon uses the 10.x.x.x range.

**Comment by sbrunner** [comment]
Yes but the 10.x.x.x is like a private network on witch one we don't want any non controlled query :-)

I Just add a second `!localMatch` to failed on hidden internal mapserver :-)

**Comment by sbrunner** [comment]
Looks good, merge :-)

**Comment by sbrunner** [comment]
Travis failed :-(

**Comment by sbrunner** [comment]
Don't looks important...

**Comment by pvalsecc** [comment]
C'est pas moi!   ;-)

**Pull request merged**
