### PR TITLE
Support data URLs in the HTTP request factory

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by gberaudo** [comment]
@sbrunner, I added data:url support to the image layer (and others based on the same http request mechanism).

 I tested this with some png data:url and it passed:
- the static image gets decoded and printed;
- it is composed by the print into the background raster layer.

What do you think?

**Comment by sbrunner** [comment]
It shouldn't use a handler as it's done here?
https://github.com/mapfish/mapfish-print/pull/1359/files?diff=unified&w=1

It should be tested throw an example...

**Comment by gberaudo** [comment]
@sbrunner, the ImageLayer and associated factories are using URIs. An Handle only works with URLs.

https://github.com/mapfish/mapfish-print/blob/master/core/src/main/java/org/mapfish/print/map/image/ImageLayer.java#L94-L95

How do you handle it?

**Comment by sbrunner** [comment]
I'm curious to know why it's an URI, but it's another story...

**Comment by gberaudo** [comment]
@sbrunner, the code is now making use of the Handler. Does it look better now?

**Comment by sbrunner** [comment]
Yes :-), and the changes in DataUrlConnection.java  can be canceled :-)

**Comment by gberaudo** [comment]
> Yes :-), and the changes in DataUrlConnection.java can be canceled :-)

Indeed @sbrunner, I forgot about it. It is done now.

**Review by sbrunner — APPROVED** [review]
Thanks :-)

**Comment by gberaudo** [comment]
@sbrunner, I changed the base to 3.20 so the build should soon pass.
OK for you to merge this in the 3.20 branch and then backport it to master?

**Comment by gberaudo** [comment]
@sbrunner, as discussed, I rebased this branch on top of master.

**Pull request merged**
