### PR TITLE
Parallel download for legend images

### PR DESCRIPTION
**Pull request by tsauerwein**
The legend processor is relatively slow, e.g. a legend with 6 entries takes about 1.5 sec. to generate. The legend processor downloads the legend images before they are inserted in a sub-report. Currently the download is not done in parallel, so the same technique as for tile layers can be applied.

Thanks @NielsCharlier for having implemented this improvement!

### CODE REVIEW

**Comment by sbrunner** [comment]
Why merging those pull request without any review?

**Comment by tsauerwein** [comment]
The work has already been reviewed. I only opened a PR to trigger Travis before merging. If you have more comments, please feel free to open a follow-up PR.

**Comment by sbrunner** [comment]
> The work has already been reviewed.

Where?

**Comment by tsauerwein** [comment]
https://github.com/camptocamp/mapfish-print-internal/pull/1

**Comment by sbrunner** [comment]
I never see that, why don't do it in the pubic repository?

**Pull request merged**
