### PR TITLE
Fixed concurrency issue in configuration file usage

### PR DESCRIPTION
**Pull request by mbarto**

### CODE REVIEW

**Comment by tsauerwein** [comment]
Thanks, that looks good!

**Comment by mbarto** [comment]
Thanks! Do you think a bug fix release for 2.1.x could be published on maven repos? We would like to include this in the GeoServer printing plugin.

**Comment by tsauerwein** [comment]
@sbrunner Do you know how the releases are made for version 2?

**Comment by sbrunner** [comment]
no, I don't know :-(

**Comment by tsauerwein** [comment]
> Thanks! Do you think a bug fix release for 2.1.x could be published on maven repos? We would like to include this in the GeoServer printing plugin.

Ok, I made a release (2.1.2). Publishing to maven takes a while, but the release should soon show up:
https://repo1.maven.org/maven2/org/mapfish/print/print-lib/

**Pull request merged**
