### PR TITLE
Upgrade JTS to org.locationtech v1.16.0 (geotools >= 20)

### PR DESCRIPTION
**Pull request by tixvieira**
- Upgrade JTS to org.locationtech v1.16.0 (geotools >= 20)
- Remove dependency of "org.mapfish.geo:mapfish-geo-lib:1.2.0"

### CODE REVIEW

**Comment by tixvieira** [comment]
http://osgeo-org.1560.x6.nabble.com/Possible-bug-with-printing-plugin-td5387582.html

https://groups.google.com/forum/#!topic/mapfish-print-users/chiSYWZFmtk

**Comment by tixvieira** [comment]
@pvalsecc , 

In the last version (2.1.3) you told the tests are not ok, so why maintain it?
https://github.com/mapfish/mapfish-print/issues/143#issuecomment-428835765

Can i remove those tests on this Pull Request too? I think the print-lib become "cleaner". :)

**Comment by tixvieira** [comment]
@pvalsecc/@sbrunner, can you make the 2.1.4 release?
After that i can do a PR on Geoserver to use this new version.
Thanks

**Comment by pvalsecc** [comment]
Hi @tixvieira,
Thanks for being the last maintainer of V2!
I've made the 2.1.4 release. It will be eventually pushed by nexus to mvnrepository.
CU

**Comment by tixvieira** [comment]
You're welcome!

Geoserver issue:
https://osgeo-org.atlassian.net/browse/GEOS-9051

**Comment by tixvieira** [comment]
> Hi @tixvieira,
> Thanks for being the last maintainer of V2!
> I've made the 2.1.4 release. It will be eventually pushed by nexus to mvnrepository.
> CU

It doesn't appear to be released on maven yet.
https://mvnrepository.com/artifact/org.mapfish.print/print-lib

Do you know what is the status of ir? Or how many time it will take to get there?

Thanks

**Comment by pvalsecc** [comment]
It takes ages to be re-indexed by them. The files are already there, though:
http://central.maven.org/maven2/org/mapfish/print/print-lib/2.1.4/

**Comment by tixvieira** [comment]
:)

Thank you very much!

**Pull request merged**
