### PR TITLE
Fix Maven dependency issues

### PR DESCRIPTION
**Pull request by tsauerwein**
Fixes https://github.com/mapfish/mapfish-print/issues/414

### CODE REVIEW

**Comment by pvalsecc** [comment]
Looks good. Please merge if Travis is happy.

**Comment by sbrunner** [comment]
+1 but Travis don't aggree :-/

**Comment by tsauerwein** [comment]
`demo.mapfish.org` was used in one of the tests, now it should pass.

**Comment by pmauduit** [comment]
looks good :+1:

**Comment by tsauerwein** [comment]
Thanks for the review.

**Pull request merged**
